### ISSUE TITLE
Only get NULL timestamp

### ISSUE THREAD

**Issue by LuNiPriSe** [ledermann/unread#118]
The mark_as_read! delivers a NULL timestamp in my app.
In the rails console it works somehow.

I assume it has somehting to do with `rm.timestamp   = self.send(readable_options[:on]) `

ruby 2.7.1
Rails 6.0.3
unread (0.11.0)

**Comment by ledermann** [comment]
Can't reproduce this. Can you build a failing test?

**Comment by LuNiPriSe** [comment]
I figured it out.. 
It was because I used a "published_at" timestamp, which could lie in the future.. confusing the unread timestamp...
All good. Thanks though
