### ISSUE TITLE
Class.mark_as_read! :all, for: user doesn't mark all as unread in a transaction

### ISSUE THREAD

**Issue by kenips** [ledermann/unread#26]
When inside a transaction, say:

```
Book.transaction do
  Book.mark_as_read! :all, for: user
  Book.unread_by(user)
end
```

would still return unread books from before the transaction. I understand that this *could* be by design, but perhaps there could be instance variables set above the persistence level to provide support for this scenario?

**Comment by ledermann** [comment]
Fixed by da253be0330f20344d6f1095f9bbbeaebc7865cd
