### ISSUE TITLE
Ability to set multiple models as readers

### ISSUE THREAD

**Issue by ezuhaib** [ledermann/unread#33]
I have a situation where I need multiple models to act as reader, however this isn't currently possible in unread gem. What would be a workaround?

**Comment by auxout** [comment]
+1

**Comment by NoNonsenseSolutions** [comment]
any workarounds for this?

**Comment by ledermann** [comment]
Currently, the database schema (see [here](https://github.com/ledermann/unread/blob/master/lib/generators/unread/migration/templates/migration.rb)) is based on a simple reference to `user`. To allow multiple models as reader, this has to be enhanced to a polymorphic association, e.g. with `reader_id` and `reader_type`. Patches are welcome ;-)
