### ISSUE TITLE
Ability to set multiple models for "notifications"

### ISSUE THREAD

**Issue by ACPK** [ledermann/unread#57]
Similar to Facebook, we have multiple models that need to be added to a user's new notification feed, i.e., photo comments, friends that uploaded a new photo, and a new friend joined the site.

**Comment by ledermann** [comment]
To achieve this, you can add `acts_as_readable` to multiple models. Now you can get unread photos, unread comments etc.

But if you want to build a notification feed with different models ordered by time, you should consider to create a separate model `Activity` with polymorphic association to a trackable model. For every new photo, comment, relationship etc, one activity has to be created. Then, use only this model as readable.

````ruby
class Activity < ActiveRecord::Base
  belongs_to :trackable, :polymorphic => true
  acts_as_readable
end

class Photo < ActiveRecord::Base
  has_one :activity, :as => :trackable
end

class Comment < ActiveRecord::Base
  has_one :activity, :as => :trackable
end
````
