### ISSUE TITLE
Support for a UUID primary key

### ISSUE THREAD

**Issue by swastik** [ledermann/unread#60]
Does this gem work with UUID as the primary key?

I looked into the source code, but couldn't find anything. I also tried it on a sample app, but it breaks on this line in `readable_scopes.rb`:

    AND read_marks.user_id        = #{user.id}

It results in something like:

    AND read_marks.user_id          = e61422-0e0c-4a49-9a4

Something like:

    AND read_marks.user_id          = 'e61422-0e0c-4a49-9a4'

... seems to work. Any ideas?

**Comment by ledermann** [comment]
Using `sanitize_sql_array` should help. I will check it out tomorrow.

**Comment by swastik** [comment]
Thank you!

**Comment by ledermann** [comment]
@swastik I've just pushed 01f9104. Does it help?

**Comment by swastik** [comment]
Yes, it does! Works perfectly now! :smiley:

**Comment by ledermann** [comment]
Fine, thanks for feedback.
