### ISSUE TITLE
Can there be an unread scope in the reader

### ISSUE THREAD

**Issue by xzhflying** [ledermann/unread#62]
I wonder if it's possible and necessary to have this kind of scope in the reader:
reader.unread(registered_model_name)
---
For example, if the User is the reader and the Notification is readable, we want to get user's unread notifications. Maybe we need this kind of scope( `user` is an instance of User) :
* `user.unread(Notification)`

It performs just like `Notification.unread_by(user)`, but maybe it can be used to custom some scopes.

For instance, if there is a type of notification called `popup`, we want to create a scope for the user called `unread_popups`. How can we do it now?

But with the new scope, we can do it like this `scope :unread_popups -> { unread(Notification).where( notification_type: 'popup') }`.

Will this be a useful suggestion? :flushed:

**Comment by ledermann** [comment]
If I get you right, the scope can be defined likes this:

```ruby
class Notification < ActiveRecord::Base
  acts_as_readable

  scope :unread_popups, ->(user) { where(notification_type: 'popup').unread_by(user) }
end
```

Does this help?

**Comment by xzhflying** [comment]
hmm.... Actually this can get the results that I want, but this may not be a good solution. My opinion is to make use of the association between models. In this case, user has_many notifications and notification belongs to the user. The most beautiful solution may be like this

`user.popups.unread`    `popup` is a scope of notification. 

My descriptions may not be correct in my first comment... Actually when you do `user.popups`, the results just have one common reader, so that you don't need to provide a reader again. At this time, if there is a scope can extract the common reader( absolutely it needs to judge if it's legal to do this) and then do the query, that will be more graceful and the code will be easier to understand.

In a word, we can just get the results starting from the readable side now( like `Notification.unread_by(user)`), but sometimes, we may need to get the same results starting from the reader( like `user.unread(popups)` or `user.popups.unread`).

**Comment by ledermann** [comment]
Ok, I understand. But what about this:

```ruby
class User  < ActiveRecord::Base
end

class Notification < ActiveRecord::Base
  acts_as_readable

  scope :popups, where(notification_type: 'popup')
end

user.popups
```

**Comment by ledermann** [comment]
Ok, I understand. But I still think we don't need to change the gem. Based on this ...

```ruby
class User  < ActiveRecord::Base
  acts_as_reader

  has_many :notifications
end

class Notification < ActiveRecord::Base
  acts_as_readable

  scope :popups, where(notification_type: 'popup')
end
```

... we can do this:

```ruby
user.notifications.popups.unread_by(user)
```

Ok, some kind of duplication, because we refer to user twice. But maybe it's not always the same user, e.g.:

```ruby
other_user.notifications.popups.unread_by(current_user)
```

**Comment by ledermann** [comment]
Additional idea (ok, some kind of a hack):

```ruby
class User  < ActiveRecord::Base
  # ....

  def unread_notifications(scope=nil)
    notifications.send(scope || :all).unread_by(self)
  end
end
```

Now you can do this:

```ruby
user.unread_notifications(:popups)
```

This eliminates the duplicated user reference.

**Comment by xzhflying** [comment]
hmm... The problem is that you need to add this kind of codes in every models that have this requirement. Also it may not be so good to put this kind of scope into the reader's model. The reader should not know the details in the readable models. I think I'll try to make a PR first, then let's discuss if it is necessary to have this kind of method. :flushed:

**Comment by xzhflying** [comment]
After the discussion, we decided to use extension in the model which is like:
```ruby
Class User < ActivityRecord::Base
  # ...

  has_many :notifications, dependent: :destroy, do
    def unread
      unread_by(proxy_association.owner)
    end
  end
end
```
Thanks for your patience and help @ledermann . :smiley:

**Comment by ledermann** [comment]
Looks good!
