### ISSUE TITLE
.cleanup_read_marks! performance?

### ISSUE THREAD

**Issue by pyro2927** [ledermann/unread#64]
The current `.cleanup_read_marks!` appears to [iterate over every entry in the table](https://github.com/ledermann/unread/blob/master/lib/unread/readable.rb#L56), checking for older entries, and then deleting all but the newest.  This could result in a lot of un-used find queries where there are no read marks that need to be cleaned for a certain `readable`.  It seems like it could be optimized by having a query with some sort of `WHERE COUNT(read_marks.id) > 1 GROUP BY readable_id, readable_type`, which would only then iterate over things that actually needed cleaning.

**Comment by ledermann** [comment]
Great hint - thank you, @pyro2927. I have made some changes, what do you think about [this commit](7d26c80)?

(To improve readability, the cleanup code was moved to a separate class named `GarbageCollector` before)

**Comment by pyro2927** [comment]
Looks awesome!

**Comment by ledermann** [comment]
Fine, I will publish the next release soon.
