### ISSUE TITLE
Does not work with non pluralized table names

### ISSUE THREAD

**Issue by rlow** [ledermann/unread#69]
We use singular table names in our apps by setting `ActiveRecord::Base.pluralize_table_names = false` in application.rb. Baked in references to "read_marks" causes SQL errors.

Would using `"#{ReadMark.table_name}"` in the sql strings in the scopes instead of `"read_marks"` fix this issue?

**Comment by ledermann** [comment]
Thanks for reporting this issue, @rlow

However, I don't like the fix, building SQL queries with [`LEFT JOIN`](https://github.com/ledermann/unread/blob/df2f4580b32fb4dc9cc1569c9b7080ad0ac5db31/lib/unread/readable_scopes.rb#L7-L12), [`SELECT`](https://github.com/ledermann/unread/blob/df2f4580b32fb4dc9cc1569c9b7080ad0ac5db31/lib/unread/readable_scopes.rb#L38-L41), [`WHERE`](https://github.com/ledermann/unread/blob/df2f4580b32fb4dc9cc1569c9b7080ad0ac5db31/lib/unread/readable_scopes.rb#L19) and [`GROUP`](https://github.com/ledermann/unread/blob/df2f4580b32fb4dc9cc1569c9b7080ad0ac5db31/lib/unread/garbage_collector.rb#L33) using ActiveRecord results in too much string interpolation. If anyone knows a cleaner way, please tell me!
