### ISSUE TITLE
Rails5 delete_all(conditions: ) deprecation warning

### ISSUE THREAD

**Issue by twairball** [ledermann/unread#70]
Hi,

Is there a `rail5` branch for testing? AFAICT `acts_as_reader` will cause deprecation warnings on `delete_all`, as below: 

````
DEPRECATION WARNING: Passing conditions to delete_all is deprecated and will be removed in Rails 5.1. To achieve the same use where(conditions).delete_all
````

**Comment by ledermann** [comment]
Please use the `master` branch, it should work with Rails 5 without any warnings

**Comment by twairball** [comment]
Yes thanks that works now -- I was just looking through source and realized :) 
:+1:
