### ISSUE TITLE
Accessing read/unread stats via another relationship

### ISSUE THREAD

**Issue by brendon** [ledermann/unread#77]
Hi there, I've spent a bit of time trying to figure this out so I thought I'd ask here in case you had any pointers :)

I have a model called `Values`. A `value` has many `comments`, and the comments readable via your gem.

I'm rendering a `document` full of `values` so I want to select all the `values` in a `document`, and also have an additional two columns: `comments_count` and `unread_comments_count`. This allows me to render the document indicating the comments as efficiently as possible. Right now I'm issuing a query for each `unread_by` call that is causing a performance problem.

I've had some success getting an `unread_count` by merging `unread_by()` into the query and forcing a `LEFT JOIN` between values and comments. But then it doesn't seem possible to get a count of all of the comments (read and unread) in that same query.

Any pointers would be greatly appreciated. :)

**Comment by brendon** [comment]
I ended up not eager loading the comments at all (as I don't actually use the objects). Instead I'm generating a statistics hash like this:

```
default_hash = Hash.new { |h, k| h[k] = { unread: 0, total: 0 } }
document.comments.with_read_marks_for(current_user).reduce(default_hash) do |hash, comment|
  hash[comment.value_id][:unread] += 1 if comment.unread?(current_user)
  hash[comment.value_id][:total] += 1
  hash
end
```

Results in one query at the start plus several (ultimately cached) queries on the `read_marks` table when there are no read_marks. Works pretty well.

**Comment by ledermann** [comment]
Using `with_read_marks_for` is the key. It uses just one query and make sure that the following `unread?` invocations use the result of the first query (see [code](https://github.com/ledermann/unread/blob/v0.8.1/lib/unread/readable.rb#L94-L102)).

Your solution looks fine.

**Comment by brendon** [comment]
Thanks @ledermann, yep it's working great. Thanks for the help :)

**Comment by Frexuz** [comment]
Just stumbled upon this. @brendon's solution was exactly what we were looking for. 

It would be a great addition to the README (the whole example?), and explaining that subsequent `unread?(user)` doesn't do an additional query. 👍 

A bit unnecessary to dig through the issues / finding it by chance :)

**Comment by brendon** [comment]
Glad I was able to be of some help @Frexuz :) I'm sure @ledermann would appreciate a PR with the documentation enhancements if you had the time to do it. Would you be keen? :)

**Comment by Frexuz** [comment]
Let me give it a go :) Then @ledermann  can adjust

**Comment by Frexuz** [comment]
https://github.com/ledermann/unread/pull/98
