### ISSUE TITLE
A lot of same requests after new reader creating

### ISSUE THREAD

**Issue by ytrrty** [ledermann/unread#79]
After creating reader (user), I getting a lot of same requests. It's creating and deleting read_mark about 18 times.

`SQL (6.7ms)  DELETE FROM "read_marks" WHERE "read_marks"."reader_id" = $1 AND "read_marks"."reader_type" = $2 AND "read_marks"."readable_type" = $3  [["reader_id", 50763], ["reader_type", "User"], ["readable_type", "Event"]]`

`SQL (11.9ms)  INSERT INTO "read_marks" ("reader_id", "reader_type", "readable_type", "timestamp") VALUES ($1, $2, $3, $4) RETURNING "id"  [["reader_id", 50763], ["reader_type", "User"], ["readable_type", "Event"], ["timestamp", "2016-09-14 13:12:51.715057"]]`

<img width="1674" alt="2016-09-14 16 24 24" src="https://cloud.githubusercontent.com/assets/7595232/18513846/c2191b6e-7a97-11e6-853f-91cebdb759a9.png">

**Comment by ledermann** [comment]
Hm, the two SQL queries (DELETE + INSERT) are from [#setup_new_reader](https://github.com/ledermann/unread/blob/master/lib/unread/reader.rb#L42-L49), which is executed as a callback for [after_create]( https://github.com/ledermann/unread/blob/master/lib/unread/base.rb#L14).

Maybe there is a class loading issue in your app? It seems to me that the `acts_as_reader` class method is executed multiple times, so the callback fires multiple times.

**Comment by ytrrty** [comment]
No, `acts_as_reader` executed one time in one model.
When I restart the server method is called again one time, but over time the number of calls increases.

**Comment by ledermann** [comment]
Didn't see this before. Do you have any more background info about the issue? What Rails version? In production or in development env?

**Comment by ledermann** [comment]
@ytrrty Please checkout my latest commit. Does this help?

**Comment by ledermann** [comment]
Should be fixed by 4b744fa8dbc96f487058ad567e73ac12db733094
