### ISSUE TITLE
Get list of records that have unread related records.

### ISSUE THREAD

**Issue by leadingproperties** [ledermann/unread#87]
I have Conversation that has_many Messages. Is there best way to get Conversations with unread messages inside? 

```
class Conversation < ApplicationRecord
  has_many :messages
end

class Message < ApplicationRecord
  acts_as_readable :on => :created_at
  belongs_to :conversation
end
```

After few hours of try's, and after I wrote this question (order thoughts) -
my solution is:
```
user = User.last
Conversation.joins(:messages).where(id: Message.unread_by(user).pluck(:conversation_id))
```
Think this query will return Conversations with unread messages inside. May be there is the better way?

**Comment by ledermann** [comment]
What about this:

````ruby
class Conversation < ApplicationRecord
  has_many :messages
  acts_as_readable_on on: :updated_at
end

class Message < ApplicationRecord
  belongs_to :conversation, touch: true
  acts_as_readable :on => :created_at
end

Conversion.unread_by(user)
````

**Comment by leadingproperties** [comment]
Thank's for quick response. You are opened my eyes with this simple solution. I review my design and notice that I don't need mark read messages at all. I can mark Conversations. Thanks!
